### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jackocnr** [behdad/region-flags#1]
Thanks for this amazing project - I'd like to use it for my popular [International Telephone Input](https://github.com/Bluefieldscom/intl-tel-input) project. I was just wondering if you would consider publishing the project as a [Bower](http://bower.io/) package?

**Comment by behdad** [comment]
I'm not well-versed with Bower.  Feel free to send a pull-request.

**Comment by jackocnr** [comment]
FYI I've now registered the package with Bower, so anyone can do `bower install region-flags` to integrate your project into theirs and keep it up to date (you must do semver tagging for updates to work).

**Comment by shervinafshar** [comment]
Thanks. I will look into this later.

↪ Shervin

**Comment by behdad** [comment]
Thanks.

**Comment by jackocnr** [comment]
Dang apparently Bower (and npm) ignore symlinks because they don't work on Windows.

Is there a way to get all the flags without symlinks?

**Comment by behdad** [comment]
Open new issue please so we can track it.
