### ISSUE TITLE
Add flag of District of Columbia

### ISSUE THREAD

**Issue by JonathanLennox** [behdad/region-flags#22]
It looks like the Flag of the District of Columbia isn't getting included.

It's on Wikimedia Commons at https://commons.wikimedia.org/wiki/File:Flag_of_Washington,_D.C..svg with a public domain license.

**Comment by Kanjilearner817** [comment]
I figure that this issue and #23 ought to be closed, since they have since been added.

**Comment by behnam** [comment]
Right. It's here: <https://github.com/behdad/region-flags/blob/gh-pages/svg/US-DC.svg>. Thanks!
