### ISSUE TITLE
Add flags of Canadian provinces and territories

### ISSUE THREAD

**Issue by JonathanLennox** [behdad/region-flags#23]
Flags of Canadian provinces and territories should be included.  SVG images of all the Canadian provinces' and territories' flags (all of which, I believe, are licensed in the public domain), are linked from https://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada .

**Comment by Kanjilearner817** [comment]
What I said in #22.

**Comment by behnam** [comment]
Right. They are here: <https://github.com/behdad/region-flags/blob/gh-pages/svg/CA-*.svg>. Thanks!
