### ISSUE TITLE
Any way to convert the SVG files of the flags for Android, to VectorDrawable files?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [behdad/region-flags#26]
This way we could use it in our apps, without the loss of quality, or without the need to have multiple density files.

**Comment by behdad** [comment]
I think last time I searched there were some Open Source projects around to do that.  Search for them.

**Comment by AndroidDeveloperLB** [comment]
Can you please provide one?

**Comment by behdad** [comment]
> Can you please provide one?

http://lmgtfy.com/?q=svg+to+android+vector+converter

**Comment by AndroidDeveloperLB** [comment]
All this gave is a single conversion. You have a lot of files. Is there one for batch conversion?
