### ISSUE TITLE
When I delete all flags and run download script, Cayman Islands PNG is tiny (36x36px)

### ISSUE THREAD

**Issue by jackocnr** [behdad/region-flags#35]
It's strange - every other flag is fine, but the Cayman Islands flag is tiny: 36x36px. In addition, it has weird curved corners, which none of the others have. Any ideas what might be causing this?

**Comment by SaveTheRbtz** [comment]
This is fixed by: e066edfc2b77df5c65c9d5ed04bd419712c1824d: https://github.com/fonttools/region-flags/commit/5e2da4401498c82c04f1c6b2cb21f489a2033dcf#diff-27c189c42b294a68d005ca7b03e9eb45128fda6adaecab6fe8dd1b6a5ce4b904
