### ISSUE TITLE
New region-flags release

### ISSUE THREAD

**Issue by SaveTheRbtz** [behdad/region-flags#48]
Seems like [the last release was 5 years ago](https://www.npmjs.com/package/region-flags). Maybe it is time to cut 1.1.1 or 1.2.0?

**Comment by behdad** [comment]
I don't think anyone depends on our releases, but sure.

Mind we making you a developer?

**Comment by behdad** [comment]
> I don't think anyone depends on our releases, but sure.

Obviously I'm wrong based on your npmjs link. :))

**Comment by SaveTheRbtz** [comment]
> Mind we making you a developer?

totally fine!

**Comment by SaveTheRbtz** [comment]
Will you create a release, or do you want me to try it?  If you want me to try it: what is the preferred version number? 1.2.0, 1.1.1, or something else?

**Comment by behdad** [comment]
Go for it. Looks like just pushing a tag it is. 1.1.0?

**Comment by behdad** [comment]
1.2.0? I don't see 1.1.0 in our repo :))

**Comment by SaveTheRbtz** [comment]
Pushed `1.1.0` pointing to 8f9781d84495da20e2c7f1a9fc10b1fb989242db, let me create 1.2.0 in ~30 mins...

**Comment by SaveTheRbtz** [comment]
Bumped package version to 1.2.0: fonttools/region-flags#49

**Comment by SaveTheRbtz** [comment]
Release draft: https://github.com/fonttools/region-flags/releases/tag/untagged-1f9c7d744c30de846627

**Comment by behdad** [comment]
Thank you!

**Comment by SaveTheRbtz** [comment]
Published: https://github.com/fonttools/region-flags/releases/tag/1.2.0

Not sure whether any additional work is needed to [publish it to npmjs](https://www.npmjs.com/package/region-flags) -- it still shows 1.1.0. (cc: @behnam)

**Comment by SaveTheRbtz** [comment]
cc: @behnam as an owner of https://www.npmjs.com/package/region-flags
