### ISSUE TITLE
Martinique (MQ) flag is outdated

### ISSUE THREAD

**Issue by bernardobelchior** [behdad/region-flags#54]
Martinique's flag (MQ) is France's flag, but [according to Wikipedia](https://en.wikipedia.org/wiki/Martinique), the flag should be:

![](https://upload.wikimedia.org/wikipedia/commons/2/27/Flag-of-Martinique.svg)

Apparently, it was adopted on February 2023:

> Martinique adopted a new flag on February 2, 2023

**Comment by behdad** [comment]
@shervinafshar Would you have time to do an update of the repo? Thanks.

**Comment by bernardobelchior** [comment]
Thank you 🙏
