### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by jackocnr** [behdad/region-flags#9]
Would you be interested in registering region-flags as a package on [NPM](https://www.npmjs.com/)? It's the most popular package manager for the JavaScript community, and adding region-flags would allow more devs to find and use it! Plus it's super easy.

There are two steps:
1. You need a package.json file in the root dir, which I can prepare in a pull request
2. You need to [install npm](https://nodejs.org/en/download/) and `cd` into the region-flags directory and run a couple of commands: `npm adduser` and follow instructions to create a new user for yourself, then `npm publish` to add region-flags to the npm index.

Let me know what you think, thanks!

**Comment by behdad** [comment]
Thanks.  Merged package.json.  I don't have npm installed.  @shervinafshar or @behnam, maybe one of you can take care of that?

**Comment by behnam** [comment]
It's now published:
https://www.npmjs.com/package/region-flags

@behdad, you can close the issue.

**Comment by jackocnr** [comment]
Great! Thanks guys!
